/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/LCf38ZLf1zW
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";
import { Card, CardContent } from "@/components/ui/card";

export default function MessageBased({
  name,
  type,
  message,
}: {
  name: string;
  type: string;
  message: {
    text: string;
    date: string;
  }[];
}) {
  console.log(message);
  return (
    <div className="w-full max-w-3xl mx-auto py-8 px-4 md:px-6">
      <header className="flex items-center gap-4 mb-6">
        <Avatar className="h-12 w-12">
          <AvatarImage src="/placeholder-user.jpg" alt="User Avatar" />
          <AvatarFallback>JD</AvatarFallback>
        </Avatar>
        <div>
          <h1 className="text-2xl font-bold">{name}</h1>
          <div className="text-sm text-muted-foreground">{type}</div>
        </div>
      </header>
      <Card>
        <CardContent className="p-6">
          <div className="text-lg font-medium mb-4">
            <h2>Messages</h2>
          </div>
          {message?.map((msg, index) => (
            <>
              <p key={index + "message"} className="text-muted-foreground">
                {msg.text}
              </p>
              <p>{msg.date}</p>
            </>
          ))}
        </CardContent>
      </Card>
    </div>
  );
}
